[tools]
tuist = { version = '4.119.4', os = ["macos"] }
periphery = { version = '3.4.0', os = ["macos"] }
swiftformat = { version = '0.58.7', os = ["macos", "linux"] }
swiftlint = { version = '0.63.0', os = ["macos", "linux"] }
sentry-cli = { version = "latest", os = ["macos"] }
pipx = { version = "latest", os = ["macos", "linux"] }
"pipx:infomaniak/importloco" = { version = '2.0.0', os = ["macos", "linux"] }
